# Spatial hidden Markov model (SHMM)
#    Copyright (C) 2015-2016  Martin Waever Pedersen, mawp@dtu.dk or wpsgodd@gmail.com
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


#' @name calc.data.likelihood
#' @title Calculate data likelihood
#' @details Calculate data likelihood
#' @param parname Character string containing the name of the variable of interest.
#' @param rep A result report as generated by running fit.shmm.
#' @param exp Take exp of the variable? TRUE/FALSE.
#' @return A matrix with four columns containing respectively: 1) the lower 95% confidence limit; 2) the parameter estimate; 3) the upper 95% confidence limit; 4) the parameter standard deviation in the domain it was estimated (log or non-log).
#' @export
#' @examples
#' inp <- calc.data.likelihood(inp)
calc.data.likelihood <- function(inp){
    if (inp$datatype == 'xy'){
        n <- inp$grid$nx * inp$grid$ny
        nt <- length(inp$obsX)
        inp$datlik$xy <- array(0, dim=c(nt, inp$grid$nx, inp$grid$ny))
        for (i in 1:nt) inp$datlik$xy[i, , ] <- outer(dnorm(inp$grid$xx, inp$obsX[i], inp$osd),
                                                   dnorm(inp$grid$yy, inp$obsY[i], inp$osd))
    }

    # Combined data likelihood for all data types
    inp$datlik$all <- matrix(0, nt, n)
    for (i in 1:nt) inp$datlik$all[i, ] <- as.vector(inp$datlik$xy[i, , ])

    return(inp)
}
