# Spatial hidden Markov model (SHMM)
#    Copyright (C) 2015-2016  Martin Waever Pedersen, mawp@dtu.dk or wpsgodd@gmail.com
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


#' @name calc.data.likelihood
#' @title Calculate data likelihood
#' @details Calculate data likelihood
#' @param parname Character string containing the name of the variable of interest.
#' @param rep A result report as generated by running fit.shmm.
#' @param exp Take exp of the variable? TRUE/FALSE.
#' @return Input list containing combined data likelihood of all data sources. Format is a matrix where nrow is equal to number of time steps, and ncol is equal to the total number of grid cells.
#' @export
#' @examples
#' inp <- calc.data.likelihood(inp)
calc.data.likelihood <- function(inp){
    fac <- time.fac()
    inp <- check.inp(inp)

    # Datlik time vector
    dt <- min(diff(inp$obstimeall))
    time <- seq(min(inp$obstimeall), max(inp$obstimeall), by=dt)
    nt <- length(time)
    inp$date <- as.POSIXct(time*24*60*60, origin='1970-01-01')
    
    if ('xy' %in% inp$datatypes & !'xy' %in% names(inp$datlik)){
        nobs <- length(inp$obs$X)
        inp$datlik$xy <- array(0, dim=c(nobs, inp$grid$nx, inp$grid$ny))
        for (i in 1:nobs){
            inp$datlik$xy[i, , ] <- outer(dnorm(inp$grid$xx, inp$obs$X[i], inp$osd),
                                          dnorm(inp$grid$yy, inp$obs$Y[i], inp$osd))
        }
    }

    if ('sst' %in% inp$datatypes & !'sst' %in% names(inp$datlik)){
        # Add code to calculate SST datlik
    }

    if ('lon' %in% inp$datatypes & !'lon' %in% names(inp$datlik)){
        # Add code to calculate Lon datlik
    }

    # Combined data likelihood for all data types
    # NOT DONE
    inp$datlik$all <- matrix(1, nt, inp$grid$n)
    for (nm in inp$datatypes){
        obstime <- as.numeric(inp$obstime[[nm]]) / fac
        inds <- match(obstime, time)
        c <- 1 # Counter
        for (i in inds){
            distr <- inp$datlik[[nm]][c, , ]
            inp$datlik$all[i, ] <- inp$datlik$all[i, ] * as.vector(distr[!inp$land])
            c <- c+1
        }
    }
    
    return(inp)
}
