# Spatial hidden Markov model (SHMM)
#    Copyright (C) 2015-2016  Martin Waever Pedersen, mawp@dtu.dk or wpsgodd@gmail.com
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

#' @name summary.shmmcls
#' @title Output a summary of a fit.shmm() run.
#' @details The output includes the parameter estimates with 95% confidence intervals, estimates of derived parameters (Bmsy, Fmsy, MSY) with 95% confidence intervals, and predictions of biomass, fishing mortality, and catch.
#' @param object A result report as generated by running fit.shmm.
#' @param ... additional arguments affecting the summary produced.
#' @return Nothing. Prints a summary to the screen.
#' @examples
#' data(pol)
#' rep <- fit.shmm(pol$albacore)
#' summary(rep)
#' @export
summary.shmmcls <- function(object, ...){
    rep <- object

}
