# Spatial hidden Markov model (SHMM)
#    Copyright (C) 2015-2016  Martin Waever Pedersen, mawp@dtu.dk or wpsgodd@gmail.com
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

#' An S4 class to represent output from a shmm fit.
#' @name shmmcls
#' @aliases shmmcls-class
#' @exportClass shmmcls
setClass("shmmcls")


#' @name test.shmm
#' @title Example of a shmm analysis.
#' @details Loads a data set, fits the model, plots the results.
#' @param dataset 
#' @return A result report as given by fit.shmm().
#' @examples
#' rep <- test.shmm()
#' @export
test.shmm <- function(){

    inp <- list()
    inp$datatype <- 'xy'

    # Parameters
    inp$ini$sdx <- 6
    inp$ini$sdy <- 5
    inp$osd <- 1 # Observation error sd
    inp$dt <- 1

    inp$grid$dx <- 1
    inp$grid$dy <- 1

    # Simulate
    inp <- sim.shmm(inp)

    # Make grid
    # X
    xmin <- min(inp$true$X) - 0.1*diff(range(inp$true$X))
    xmax <- max(inp$true$X) + 0.1*diff(range(inp$true$X))
    inp$grid$xx <- seq(xmin, xmax, by=inp$grid$dx)
    inp$grid$nx <- length(inp$grid$xx)
    # Y
    ymin <- min(inp$true$Y) - 0.1*diff(range(inp$true$Y))
    ymax <- max(inp$true$Y) + 0.1*diff(range(inp$true$Y))
    inp$grid$yy <- seq(ymin, ymax, by=inp$grid$dy)
    inp$grid$ny <- length(inp$grid$yy)
    # Land
    indsy <- which(inp$grid$yy > 6 & inp$grid$yy < 8)
    indsx <- which(inp$grid$xx > 1 & inp$grid$xx < 4)
    dummy <- matrix(0, inp$grid$nx, inp$grid$ny)
    #dummy[indsx, indsy] <- 1
    inp$land <- which(dummy==1)
    cat('nx: ', inp$grid$nx, ' ny: ', inp$grid$ny, ' no states: ', inp$grid$nx*inp$grid$ny, '\n')

    # Calculate data likelihood
    inp <- calc.data.likelihood(inp)
    
    # Fit shmm
    rep <- fit.shmm(inp)

    return(rep)
}


#' @name get.par
#' @title Extract parameters from a result report as generated by fit.shmm.
#' @details Helper function for extracting the value and uncertainty of a specific model parameter or derived quantity.
#' @param parname Character string containing the name of the variable of interest.
#' @param rep A result report as generated by running fit.shmm.
#' @param exp Take exp of the variable? TRUE/FALSE.
#' @return A matrix with four columns containing respectively: 1) the lower 95% confidence limit; 2) the parameter estimate; 3) the upper 95% confidence limit; 4) the parameter standard deviation in the domain it was estimated (log or non-log).
#' @export
#' @examples
#' logD <- get.par('logD', rep, exp=TRUE)
get.par <- function(parname, rep=rep, exp=FALSE){
}


#' @name invlogit
#' @title Inverse logit transform.
#' @param a Value to take inverse logit of.
#' @return Inverse logit.
invlogit <- function(a) 1/(1+exp(-a))


#' @name invlogp1
#' @title Inverse log "plus one" transform
#' @details If a = log(b-1), then the inverse transform is b = 1 + exp(a). Useful for values with lower bound at 1.
#' @param a Value to take inverse logp1 of.
#' @return Inverse logp1.
invlogp1 <- function(a) 1 + exp(a)
